Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,5 +1,3 @@
-# Sample repository at https://github.com/Novfensec/SAMPLE-KIVYMD-APP
-
 name: CI - Android
 
 on:
@@ -12,16 +10,14 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-20.04  # Use Ubuntu 20.04 to support missing dependencies
 
     steps:
       - uses: actions/checkout@v4
 
-      # Used to cache dependencies with a timeout
       - name: Get Date
         id: get-date
-        run: |
-          echo "date=$(date -u '+%Y%m%d')" >> $GITHUB_ENV
+        run: echo "date=$(date -u '+%Y%m%d')" >> $GITHUB_ENV
         shell: bash
 
       - name: Cache Buildozer global directory
@@ -52,8 +48,7 @@ jobs:
             libavformat-dev \
             libavcodec-dev \
             libunwind-dev \
-            zlib1g-dev
-          sudo apt-get install -y \
+            zlib1g-dev \
             libsqlite3-dev \
             sqlite3 \
             bzip2 \
@@ -67,8 +62,7 @@ jobs:
             uuid-dev \
             libgstreamer1.0 \
             gstreamer1.0-plugins-base \
-            gstreamer1.0-plugins-good
-          sudo apt-get install -y \
+            gstreamer1.0-plugins-good \
             zip \
             unzip \
             autoconf \
@@ -76,24 +70,29 @@ jobs:
             pkg-config \
             libncurses5-dev \
             libncursesw5-dev \
-            libtinfo5 \
             cmake \
             libffi-dev \
             libssl-dev \
             automake
 
+      - name: Add old package repository for libtinfo5 (if needed)
+        run: |
+          sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu focal main universe"
+          sudo apt update
+          sudo apt-get install -y libtinfo5 || echo "libtinfo5 not required"
+
       # Set up Java 17 required by Gradle
       - name: Setup Java 17 required by Gradle
         uses: actions/setup-java@v4
         with:
-          distribution: 'temurin'  # or 'zulu', 'liberica', etc.
+          distribution: 'temurin'
           java-version: '17'
 
       # Set up Python
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
-          python-version: '3.8' #set your python version
+          python-version: '3.8'
 
       # Install pip dependencies
       - name: Install pip dependencies
@@ -106,8 +105,6 @@ jobs:
         id: buildozer
         run: |
           yes | buildozer -v android debug
-        # yes | buildozer -v android release
-        # run this for generating aab (Android App Bundle) [Required by google play]
 
       # Upload artifacts
       - name: Upload artifact
